data_transformation:
  input_column: "dialogue"
  target_column: "summary"
  max_input_length: 512
  max_target_length: 128

model_trainer:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000
  gradient_accumulation_steps: 16
  model_name: "google/pegasus-xsum"