artifacts_root: artifacts

artifacts:
  data_ingestion:
    root_dir: artifacts/data_ingestion
    ingested_train_dir: artifacts/data_ingestion/ingested_train
    ingested_test_dir: artifacts/data_ingestion/ingested_test
    dataset_name: "knkarthick/samsum"

  data_transformation:
    root_dir: artifacts/data_transformation
    tokenizer_name: "google/pegasus-xsum"

  model_trainer:
    root_dir: artifacts/model_trainer

  model_evaluation:
    root_dir: artifacts/model_evaluation
    metric_file_name: rouge_scores.csv
